### ISSUE TITLE
add fulltext search 

### ISSUE THREAD

**Issue by Azuna1** [kokarn/ARK-Dev-Tracker#11]
for all recent posts, not just 1 page

**Comment by kokarn** [comment]
It's not just 1 page at the moment, it just lists the 100 most recent posts. 
What are you having trouble with?

**Comment by Azuna1** [comment]
well for when you add pagination
and as stated, for all posts not just 1 page or last 100

**Comment by kokarn** [comment]
The search right now searches through all posts, isn't that what you want? 
The only limit currently is that it will only display up to 100 results from all posts when you search.

I will add pagination but isn't the search what you want or is it actually pagination?

Sorry if i don't get it, just trying to figure out if you want something that's not already added :)

**Comment by Azuna1** [comment]
eh i failed sorry
the search is so well integrated thats its already hidden!

i looked for a search function (started on the right top side) and didnt find one
now after your post i ctrl+f "search" and found it on the left top pretty greyed out on a white background :)

**Comment by kokarn** [comment]
Ah, yeah i'm working on making it easier to see. Great that it's solved!
