### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by kokarn** [kokarn/ARK-Dev-Tracker#14]

**Comment by beepFTW** [comment]
Thanks so much!

**Comment by kokarn** [comment]
This is now live! 

The feed is located at: http://arkdevtracker.com/actions/rss.php

**Comment by RogerSik** [comment]
It doesn't work. Its empty. :(

**Comment by kokarn** [comment]
It works great for me. Is it still broken for you?

**Comment by RogerSik** [comment]
Dont work for me. 

Firefox shows nothing and my web RSS reader (selfoss) shows following error

```
2016-01-07 13:54:29error loading feed content: This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 248, column 16477 
```

**Comment by kokarn** [comment]
This should work now. Found some minor things that I improved :)

**Comment by RogerSik** [comment]
Works (in selfoss and firefox) for me. Thank you. :)

**Comment by kokarn** [comment]
:+1:
