### ISSUE TITLE
Can you add new webpage hub?

### ISSUE THREAD

**Issue by Neizan93** [kokarn/ARK-Dev-Tracker#19]

**Comment by Neizan93** [comment]
can you add unreal engine forums (ark dev kit and mooders sectioh)?

**Comment by Neizan93** [comment]
can you add twitter of devs?

**Comment by kokarn** [comment]
Twitter sounds like a good plan, if they have accounts that talk mostly about development of the game. Do you have any suggested accounts? That's already tracked in #3 however.

Would you mind refining this issue a bit? What is it that you want? What is 'webpage hub' ?

**Comment by kokarn** [comment]
Duplicate of #3 and #20
