### ISSUE TITLE
Unable to open database connection

### ISSUE THREAD

**Issue by Matthew2D** [kokarn/ARK-Dev-Tracker#28]
When I go to /actions/setup.php I get the following error:

`Unable to open database connection

could not find driver`

I can't find where to put the database information in the files.

Thank you!

**Comment by kokarn** [comment]
The whole project has moved. I should probably update the readme about that...
It's not located at https://github.com/post-tracker

What part is it you're trying to run?

**Comment by Matthew2D** [comment]
I'm trying to run a dev tracker for a game. So it was moved to https://github.com/post-tracker?

**Comment by Matthew2D** [comment]
Do you have a discord?

**Comment by kokarn** [comment]
Yeah, it's much more complex now.

I'm more than happy to just start tracking the game you want.

Hit me up on kokarn@gmail.com or Discord or whatever and we can talk.

**Comment by Matthew2D** [comment]
Okay I sent you an email!
