### ISSUE TITLE
Setting up a mirror

### ISSUE THREAD

**Issue by warezit** [kokarn/ARK-Dev-Tracker#8]
Hi all!

I am new to Node.js, but NOT new to running servers (web or gaming), therefore I am not a _complete_ idiot when it comes to these things. But, I am running into some errors when trying to setup a mirror for this.

I installed `npm` on my CentOS 6.5 server successfully.

Then I went to install `grunt watch` using:
`npm install grunt-contrib-watch --save-dev`

and I see that `grunt watch`requires an older version of glob than what comes with the Ark-Dev-Tracker git repo. It DOES say it WILL still load though. Console image here:
![image](https://cloud.githubusercontent.com/assets/8278779/8640434/fee58dde-28bd-11e5-9530-e1462754311c.png)

Then I ran `npm install` and `grunt watch`, and this is what I am getting:
![image](https://cloud.githubusercontent.com/assets/8278779/8640444/4f1d8090-28be-11e5-9aea-90e3f2cb351f.png)

Using `grunt watch --force` doesn't work either.
![image](https://cloud.githubusercontent.com/assets/8278779/8640445/7d9da1c0-28be-11e5-96d1-f3d4ffed92fe.png)

I noticed that it's complaining that it can't find the `fbtransform` module. the `fbtransform` module seems to be a part of the `React` module. (or, a sub-module called `react-tools`) I have also installed both of those successfully, and still run into the same error, complaining about missing the `fbtransform` module.

After all of this, I have tried running:
`rm -rf node_modules/`
`npm install`
and I still am getting the same errors...

Any thoughts/ideas/advice? What am I doing wrong/missing?

Thank you in advance for any/all help!
- warezit

**Comment by kokarn** [comment]
Grunt, react and all that jazz is only needed for development, so you can skip it all together.

Just run a regular web server and it should work as intended.

**Comment by warezit** [comment]
Thank you for the response.

I have since completely wiped my install of this, and I am re-trying it today.

In the current `README.MD`, it states:

> To run a mirror or something
> 
> Clone repository git clone https://github.com/kokarn/ARK-Dev-Tracker.git
> Run actions/setup.php from the web to add all the current devs
> Set something like cron to run actions/update.php as often as you like
> Done. It should now be accessible if you just browse to the folder where index.html is

BUT, when accessing /actions/setup.php, I get:

> Unable to open database connection
> SQLSTATE[HY000] [14] unable to open database file

So, I investigated, and I see that `/includes/config.php` calls for the file `/../data/arkdevtracker.sqlite`. This "data" folder, OR the .sqlite file don't exist anywhere. And, yes I know `/../` means to go up the folder tree by one folder.

I have tried cloning the repo, as well as downloading the .zip.

Any help/advice?

**Comment by kokarn** [comment]
Ah yeah, maybe i should mention that in the readme....

You need to create the data folder and arkdevtracker.sqlite file with the
correct owner and/or permissions.

Usually this should work

mkdir data
cd data
touch arkdevtracker.sqlite
chmod 777 arkdevtracker.sqlite

**Comment by warezit** [comment]
Finally got it fixed, up and running, here: http://107.170.34.165/adt/

I simply pulled the `.sqlite` file from the official dev tracker @ arkdevtracker.com, and uploaded it to the `data` folder you mentioned. Simply creating an empty `.sqlite` file, and setting perms to `777` wasn't enough.

Hope this helps! Cheers, and thanks for helping point me in the right direction! :+1:
